# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        10,
        _('States'),
        ['lineasDepto'],
        [],
[
    (_('Andhra Pradesh'), _('Is south')),
    (_('Arunachal Pradesh'), _('Is northeast')),
    (_('Assam'), _('Is east')),
    (_('Bihar'), _('Is northeast')),
    (_('Chhattisgarh'), _('Is in the center')),
    (_('Goa'), _('Is southwest')),
    (_('Gujarat'), _('Is west')),
    (_('Haryana'), _('Is northwest')),
    (_('Himachal Pradesh'), _('Is north')),
    (_('Jammu and Kashmir'), _('Is north')),
    (_('Jharkhand'), _('Is in the center')),
    (_('Karnataka'), _('Is southwest')),
    (_('Kerala'), _('Is south')),
    (_('Madhya Pradesh'), _('Is in the center')),
    (_('Maharashtra'), _('Is west')),
    (_('Manipur'), _('Is east')),
    (_('Meghalaya'), _('Is east')),
    (_('Mizoram'), _('Is east')),
    (_('Nagaland'), _('Is east')),
    (_('Orissa'), _('Is east')),
    (_('Punjab'), _('Is northwest')),
    (_('Rajasthan'), _('Is northwest')),
    (_('Sikkim'), _('Is northeast')),
    (_('Tamil Nadu'), _('Is south')),
    (_('Tripura'), _('Is east')),
    (_('Uttar Pradesh'), _('Is north')),
    (_('Uttarakhand'), _('Is north')),
    (_('West Bengal'), _('Is west')),
    # UNION
    (_('Andaman and Nicobar Islands'), _('Is southeast')),
    #Chandigarh, 225, , , 0
    (_('Dadra and Nagar Haveli'), _('Is west')),
    #Daman and Diu, 223, , , 0
    (_('Lakshadweep'), _('Is southwest')),
    #Pondicherry, 221, , , 0
    (_('Delhi'), _('Is north'))
]
]

LEVEL2 = [
        2,
        _('State capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('New Delhi'), _('Is in %s') % _('New Delhi')),
    (_('Hyderabad'), _('Is in %s') % _('Andhra Pradesh')),
    (_('Itanagar'), _('Is in %s') % _('Arunachal Pradesh')),
    (_('Dispur'), _('Is in %s') % _('Assam')),
    (_('Patna'), _('Is in %s') % _('Bihar')),
    (_('Raipur'), _('Is in %s') % _('Chhattisgarh')),
    (_('Panaji'), _('Is in %s') % _('Goa')),
    (_('Gandhinagar'), _('Is in %s') % _('Gujarat')),
    (_('Chandigarh'), _('Is in %s') % _('Haryana')),
    (_('Shimla'), _('Is in %s') % _('Himachal Pradesh')),
    (_('Srinagar'), _('Is in %s') % _('Jammu and Kashmir')),
    (_('Ranchi'), _('Is in %s') % _('Jharkhand')),
    (_('Bengalooru'), _('Is in %s') % _('Karnataka')),
    (_('Thiruvananthapuram'), _('Is in %s') % _('Kerala')),
    (_('Bhopal'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Mumbai'), _('Is in %s') % _('Maharashtra')),
    (_('Imphal'), _('Is in %s') % _('Manipur')),
    (_('Shillong'), _('Is in %s') % _('Meghalaya')),
    (_('Aizawl'), _('Is in %s') % _('Mizoram')),
    (_('Kohima'), _('Is in %s') % _('Nagaland')),
    (_('Bhubaneswar'), _('Is in %s') % _('Orissa')),
    (_('Jaipur'), _('Is in %s') % _('Rajasthan')),
    (_('Gangtok'), _('Is in %s') % _('Sikkim')),
    (_('Chennai'), _('Is in %s') % _('Tamil Nadu')),
    (_('Agartala'), _('Is in %s') % _('Tripura')),
    (_('Lucknow'), _('Is in %s') % _('Uttar Pradesh')),
    (_('Dehradun'), _('Is in %s') % _('Uttarakhand')),
    (_('Kolkata'), _('Is in %s') % _('West Bengal')),
    (_('Port Blair'), _('Is in %s') % _('Andaman and Nicobar Islands')),
    (_('Silvassa'), _('Is in %s') % _('Dadra and Nagar Haveli')),
    (_('Daman'), _('Is in %s') % _('Daman and Diu')),
    (_('Kavaratti'), _('Is in %s') % _('Lakshadweep')),
    (_('Pondicherry'), _('Is in %s') % _('Pondicherry'))
]
]


LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('New Delhi'), _('Is in %s') % _('New Delhi')),
    (_('Hyderabad'), _('Is in %s') % _('Andhra Pradesh')),
    (_('Itanagar'), _('Is in %s') % _('Arunachal Pradesh')),
    (_('Dispur'), _('Is in %s') % _('Assam')),
    (_('Patna'), _('Is in %s') % _('Bihar')),
    (_('Raipur'), _('Is in %s') % _('Chhattisgarh')),
    (_('Panaji'), _('Is in %s') % _('Goa')),
    (_('Gandhinagar'), _('Is in %s') % _('Gujarat')),
    (_('Chandigarh'), _('Is in %s') % _('Haryana')),
    (_('Shimla'), _('Is in %s') % _('Himachal Pradesh')),
    (_('Srinagar'), _('Is in %s') % _('Jammu and Kashmir')),
    (_('Ranchi'), _('Is in %s') % _('Jharkhand')),
    (_('Bengalooru'), _('Is in %s') % _('Karnataka')),
    (_('Thiruvananthapuram'), _('Is in %s') % _('Kerala')),
    (_('Bhopal'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Mumbai'), _('Is in %s') % _('Maharashtra')),
    (_('Imphal'), _('Is in %s') % _('Manipur')),
    (_('Shillong'), _('Is in %s') % _('Meghalaya')),
    (_('Aizawl'), _('Is in %s') % _('Mizoram')),
    (_('Kohima'), _('Is in %s') % _('Nagaland')),
    (_('Bhubaneswar'), _('Is in %s') % _('Orissa')),
    (_('Jaipur'), _('Is in %s') % _('Rajasthan')),
    (_('Gangtok'), _('Is in %s') % _('Sikkim')),
    (_('Chennai'), _('Is in %s') % _('Tamil Nadu')),
    (_('Agartala'), _('Is in %s') % _('Tripura')),
    (_('Lucknow'), _('Is in %s') % _('Uttar Pradesh')),
    (_('Dehradun'), _('Is in %s') % _('Uttarakhand')),
    (_('Kolkata'), _('Is in %s') % _('West Bengal')),
    (_('Port Blair'), _('Is in %s') % _('Andaman and Nicobar Islands')),
    (_('Silvassa'), _('Is in %s') % _('Dadra and Nagar Haveli')),
    (_('Daman'), _('Is in %s') % _('Daman and Diu')),
    (_('Kavaratti'), _('Is in %s') % _('Lakshadweep')),
    (_('Pondicherry'), _('Is in %s') % _('Pondicherry')),
    (_('Amarnath'), _('Is in %s') % _('Jammu and Kashmir')),
    (_('Leh'), _('Is in %s') % _('Jammu and Kashmir')),
    #(_('Gulmarg'), _('Is in %s') % _('Jammu and Kashmir')),
    #(_('Pahalgam'), _('Is in %s') % _('Jammu and Kashmir')),
    (_('Vaishno Devi'), _('Is in %s') % _('Jammu and Kashmir')),
    (_('Patni Top'), _('Is in %s') % _('Jammu and Kashmir')),
    (_('Chamba'), _('Is in %s') % _('Himachal Pradesh')),
    (_('Manali'), _('Is in %s') % _('Himachal Pradesh')),
    #(_('Dharamshala'), _('Is in %s') % _('Himachal Pradesh')),
    #(_('Kullu'), _('Is in %s') % _('Himachal Pradesh')),
    #(_('Kufri'), _('Is in %s') % _('Himachal Pradesh')),
    (_('Amritsar'), _('Is in %s') % _('Punjab')),
    (_('Atari'), _('Is in %s') % _('Punjab')),
    (_('Bathinda'), _('Is in %s') % _('Punjab')),
    #(_('Kurukshetra'), _('Is in %s') % _('Haryana')),
    (_('Panipat'), _('Is in %s') % _('Haryana')),
    #(_('Surajkund'), _('Is in %s') % _('Haryana')),
    (_('Kedarnath'), _('Is in %s') % _('Uttarakhand')),
    (_('Badrinath'), _('Is in %s') % _('Uttarakhand')),
    #(_('Mussoorie'), _('Is in %s') % _('Uttarakhand')),
    #(_('Rishikesh'), _('Is in %s') % _('Uttarakhand')),
    #(_('Haridwar'), _('Is in %s') % _('Uttarakhand')),
    (_('Nainital'), _('Is in %s') % _('Uttarakhand')),
    (_('Sravasti'), _('Is in %s') % _('Uttar Pradesh')),
    (_('Ayodhya'), _('Is in %s') % _('Uttar Pradesh')),
    #(_('Mathura'), _('Is in %s') % _('Uttar Pradesh')),
    (_('Agra'), _('Is in %s') % _('Uttar Pradesh')),
    (_('Kanpur'), _('Is in %s') % _('Uttar Pradesh')),
    #(_('Sarnath'), _('Is in %s') % _('Uttar Pradesh')),
    (_('Varanasi'), _('Is in %s') % _('Uttar Pradesh')),
    (_('Allahabad'), _('Is in %s') % _('Uttar Pradesh')),
    (_('Tezpur'), _('Is in %s') % _('Assam')),
    #(_('Guwahati'), _('Is in %s') % _('Assam')),
    #(_('Kalimpong'), _('Is in %s') % _('West Bengal')),
    (_('Darjeeling'), _('Is in %s') % _('West Bengal')),
    (_('Murshidabad'), _('Is in %s') % _('West Bengal')),
    (_('Shantiniketan'), _('Is in %s') % _('West Bengal')),
    (_('Digha'), _('Is in %s') % _('West Bengal')),
    (_('Hazaribag'), _('Is in %s') % _('Jharkhand')),
    #(_('Vaishali'), _('Is in %s') % _('Bihar')),
    (_('Bihar-Sharif'), _('Is in %s') % _('Bihar')),
    (_('Nalanda'), _('Is in %s') % _('Bihar')),
    #(_('Rajgir'), _('Is in %s') % _('Bihar')),
    #(_('Gaya'), _('Is in %s') % _('Bihar')),
    (_('Bodhgaya'), _('Is in %s') % _('Bihar')),
    (_('Pillani'), _('Is in %s') % _('Rajasthan')),
    #(_('Deeg'), _('Is in %s') % _('Rajasthan')),
    (_('Bikaner'), _('Is in %s') % _('Rajasthan')),
    (_('Jaisalmer'), _('Is in %s') % _('Rajasthan')),
    #(_('Ajmer Pushkar'), _('Is in %s') % _('Rajasthan')),
    (_('Jodhpur'), _('Is in %s') % _('Rajasthan')),
    (_('Ranakpur'), _('Is in %s') % _('Rajasthan')),
    #(_('Sawai Madhopur'), _('Is in %s') % _('Rajasthan')),
    (_('Bundi'), _('Is in %s') % _('Rajasthan')),
    (_('Kota'), _('Is in %s') % _('Rajasthan')),
    (_('Chittaurgarh'), _('Is in %s') % _('Rajasthan')),
    (_('Mount Abu'), _('Is in %s') % _('Rajasthan')),
    #(_('Udaipur'), _('Is in %s') % _('Rajasthan')),
    (_('Gwalior'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Shivpuri'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Orchna'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Khajuraho'), _('Is in %s') % _('Madhya Pradesh')),
    #(_('Chitrakut'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Sanchi'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Ujjain'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Indore'), _('Is in %s') % _('Madhya Pradesh')),
    #(_('Mandu'), _('Is in %s') % _('Madhya Pradesh')),
    #(_('Pachmarhi'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Jabalpur'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Amarkantak'), _('Is in %s') % _('Madhya Pradesh')),
    (_('Ambikapur'), _('Is in %s') % _('Chhattisgarh')),
    (_('Chitrakote Falls'), _('Is in %s') % _('Chhattisgarh')),
    (_('Hirakud Dam'), _('Is in %s') % _('Orissa')),
    (_('Cuttak'), _('Is in %s') % _('Orissa')),
    (_('Paradwip'), _('Is in %s') % _('Orissa')),
    (_('Konarak'), _('Is in %s') % _('Orissa')),
    (_('Puri'), _('Is in %s') % _('Orissa')),
    (_('Gopalpur'), _('Is in %s') % _('Orissa')),
    (_('Bhuj'), _('Is in %s') % _('Gujarat')),
    #(_('Kandla'), _('Is in %s') % _('Gujarat')),
    (_('Lothal'), _('Is in %s') % _('Gujarat')),
    (_('Vadodara'), _('Is in %s') % _('Gujarat')),
    #(_('Jamnagar'), _('Is in %s') % _('Gujarat')),
    (_('Dwarka'), _('Is in %s') % _('Gujarat')),
    (_('Rajkot'), _('Is in %s') % _('Gujarat')),
    (_('Porbandar'), _('Is in %s') % _('Gujarat')),
    (_('Somnath'), _('Is in %s') % _('Gujarat')),
    (_('Diu'), _('Is in %s') % _('Gujarat')),
    #(_('Palitana'), _('Is in %s') % _('Gujarat')),
    (_('Bhavnagar'), _('Is in %s') % _('Gujarat')),
    (_('Saputara'), _('Is in %s') % _('Gujarat')),
    (_('Malghat'), _('Is in %s') % _('Maharashtra')),
    (_('Wardha'), _('Is in %s') % _('Maharashtra')),
    #(_('Sewagram'), _('Is in %s') % _('Maharashtra')),
    (_('Chandrapur'), _('Is in %s') % _('Maharashtra')),
    (_('Ajanta'), _('Is in %s') % _('Maharashtra')),
    (_('Ellora'), _('Is in %s') % _('Maharashtra')),
    (_('Aurangabad'), _('Is in %s') % _('Maharashtra')),
    (_('Shirdi'), _('Is in %s') % _('Maharashtra')),
    #(_('Nasik'), _('Is in %s') % _('Maharashtra')),
    #(_('Matheran'), _('Is in %s') % _('Maharashtra')),
    #(_('Lonavala'), _('Is in %s') % _('Maharashtra')),
    (_('Pune'), _('Is in %s') % _('Maharashtra')),
    (_('Murud'), _('Is in %s') % _('Maharashtra')),
    (_('Mahabaleshwar'), _('Is in %s') % _('Maharashtra')),
    (_('Ganpatipule'), _('Is in %s') % _('Maharashtra')),
    (_('Panhala'), _('Is in %s') % _('Maharashtra')),
    (_('Warangal'), _('Is in %s') % _('Andhra Pradesh')),
    (_('Visakhapatnam'), _('Is in %s') % _('Andhra Pradesh')),
    (_('Bhadrachalan'), _('Is in %s') % _('Andhra Pradesh')),
    (_('Amaravati'), _('Is in %s') % _('Andhra Pradesh')),
    (_('Srisailam'), _('Is in %s') % _('Andhra Pradesh')),
    (_('Lepakshi'), _('Is in %s') % _('Andhra Pradesh')),
    (_('Tirupati'), _('Is in %s') % _('Andhra Pradesh')),
    (_('Vasco da Gama'), _('Is in %s') % _('Goa')),
    (_('Bider'), _('Is in %s') % _('Karnataka')),
    (_('Gulbarga'), _('Is in %s') % _('Karnataka')),
    (_('Bijapur'), _('Is in %s') % _('Karnataka')),
    (_('Raichur'), _('Is in %s') % _('Karnataka')),
    (_('Hampi'), _('Is in %s') % _('Karnataka')),
    (_('Jog Falls'), _('Is in %s') % _('Karnataka')),
    (_('Chitradurga'), _('Is in %s') % _('Karnataka')),
    (_('Udupi'), _('Is in %s') % _('Karnataka')),
    (_('Mangalore'), _('Is in %s') % _('Karnataka')),
    #(_('Halebid'), _('Is in %s') % _('Karnataka')),
    (_('Belur'), _('Is in %s') % _('Karnataka')),
    #(_('Mysore'), _('Is in %s') % _('Karnataka')),
    (_('Kozhikode'), _('Is in %s') % _('Kerala')),
    (_('Kochi'), _('Is in %s') % _('Kerala')),
    (_('Alappuzha'), _('Is in %s') % _('Kerala')),
    #(_('Munnar'), _('Is in %s') % _('Kerala')),
    #(_('Thekkadi'), _('Is in %s') % _('Kerala')),
    #(_('Periyar'), _('Is in %s') % _('Kerala')),
    #(_('Kanchipuram'), _('Is in %s') % _('Tamil Nadu')),
    (_('Mamallpuram'), _('Is in %s') % _('Tamil Nadu')),
    (_('Chidambaram'), _('Is in %s') % _('Tamil Nadu')),
    (_('Mudumali'), _('Is in %s') % _('Tamil Nadu')),
    #(_('Udagamandalam'), _('Is in %s') % _('Tamil Nadu')),
    #(_('Tiruchchirapalli'), _('Is in %s') % _('Tamil Nadu')),
    (_('Thanjavur'), _('Is in %s') % _('Tamil Nadu')),
    #(_('Palani'), _('Is in %s') % _('Tamil Nadu')),
    (_('Kodaikanal'), _('Is in %s') % _('Tamil Nadu')),
    (_('Madurai'), _('Is in %s') % _('Tamil Nadu')),
    #(_('Kovalam'), _('Is in %s') % _('Tamil Nadu')),
    (_('Kanniyakumari'), _('Is in %s') % _('Tamil Nadu')),
    (_('Rameswaram'), _('Is in %s') % _('Tamil Nadu'))    
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3]


