# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        10,
        _('States'),
        ['lineasDepto'],
        [],
[
    (_('Andhra Pradesh'), _('It is in the south')),
    (_('Arunachal Pradesh'), _('It is in the northeast')),
    (_('Assam'), _('It is in the east')),
    (_('Bihar'), _('It is in the northeast')),
    (_('Chhattisgarh'), _('It is in the center')),
    (_('Goa'), _('It is in the southwest')),
    (_('Gujarat'), _('It is in the west')),
    (_('Haryana'), _('It is in the northwest')),
    (_('Himachal Pradesh'), _('It is in the north')),
    (_('Jammu and Kashmir'), _('It is in the north')),
    (_('Jharkhand'), _('It is in the center')),
    (_('Karnataka'), _('It is in the southwest')),
    (_('Kerala'), _('It is in the south')),
    (_('Madhya Pradesh'), _('It is in the center')),
    (_('Maharashtra'), _('It is in the west')),
    (_('Manipur'), _('It is in the east')),
    (_('Meghalaya'), _('It is in the east')),
    (_('Mizoram'), _('It is in the east')),
    (_('Nagaland'), _('It is in the east')),
    (_('Orissa'), _('It is in the east')),
    (_('Punjab'), _('It is in the northwest')),
    (_('Rajasthan'), _('It is in the northwest')),
    (_('Sikkim'), _('It is in the northeast')),
    (_('Tamil Nadu'), _('It is in the south')),
    (_('Tripura'), _('It is in the east')),
    (_('Uttar Pradesh'), _('It is in the north')),
    (_('Uttarakhand'), _('It is in the north')),
    (_('West Bengal'), _('It is in the west')),
    # UNION
    (_('Andaman and Nicobar Islands'), _('It is in the southeast')),
    (_('Dadra and Nagar Haveli'), _('It is in the west')),
    (_('Lakshadweep'), _('It is in the southwest')),
    (_('Delhi'), _('It is in the north'))
]
]

LEVEL2 = [
        2,
        _('State capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('New Delhi'), _('It is in %s') % _('New Delhi')),
    (_('Hyderabad'), _('It is in %s') % _('Andhra Pradesh')),
    (_('Itanagar'), _('It is in %s') % _('Arunachal Pradesh')),
    (_('Dispur'), _('It is in %s') % _('Assam')),
    (_('Patna'), _('It is in %s') % _('Bihar')),
    (_('Raipur'), _('It is in %s') % _('Chhattisgarh')),
    (_('Panaji'), _('It is in %s') % _('Goa')),
    (_('Gandhinagar'), _('It is in %s') % _('Gujarat')),
    (_('Chandigarh'), _('It is in %s') % _('Haryana')),
    (_('Shimla'), _('It is in %s') % _('Himachal Pradesh')),
    (_('Srinagar'), _('It is in %s') % _('Jammu and Kashmir')),
    (_('Ranchi'), _('It is in %s') % _('Jharkhand')),
    (_('Bengalooru'), _('It is in %s') % _('Karnataka')),
    (_('Thiruvananthapuram'), _('It is in %s') % _('Kerala')),
    (_('Bhopal'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Mumbai'), _('It is in %s') % _('Maharashtra')),
    (_('Imphal'), _('It is in %s') % _('Manipur')),
    (_('Shillong'), _('It is in %s') % _('Meghalaya')),
    (_('Aizawl'), _('It is in %s') % _('Mizoram')),
    (_('Kohima'), _('It is in %s') % _('Nagaland')),
    (_('Bhubaneswar'), _('It is in %s') % _('Orissa')),
    (_('Jaipur'), _('It is in %s') % _('Rajasthan')),
    (_('Gangtok'), _('It is in %s') % _('Sikkim')),
    (_('Chennai'), _('It is in %s') % _('Tamil Nadu')),
    (_('Agartala'), _('It is in %s') % _('Tripura')),
    (_('Lucknow'), _('It is in %s') % _('Uttar Pradesh')),
    (_('Dehradun'), _('It is in %s') % _('Uttarakhand')),
    (_('Kolkata'), _('It is in %s') % _('West Bengal')),
    (_('Port Blair'), _('It is in %s') % _('Andaman and Nicobar Islands')),
    (_('Silvassa'), _('It is in %s') % _('Dadra and Nagar Haveli')),
    (_('Daman'), _('It is in %s') % _('Daman and Diu')),
    (_('Kavaratti'), _('It is in %s') % _('Lakshadweep')),
    (_('Pondicherry'), _('It is in %s') % _('Pondicherry'))
]
]


LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('New Delhi'), _('It is in %s') % _('New Delhi')),
    (_('Hyderabad'), _('It is in %s') % _('Andhra Pradesh')),
    (_('Itanagar'), _('It is in %s') % _('Arunachal Pradesh')),
    (_('Dispur'), _('It is in %s') % _('Assam')),
    (_('Patna'), _('It is in %s') % _('Bihar')),
    (_('Raipur'), _('It is in %s') % _('Chhattisgarh')),
    (_('Panaji'), _('It is in %s') % _('Goa')),
    (_('Gandhinagar'), _('It is in %s') % _('Gujarat')),
    (_('Chandigarh'), _('It is in %s') % _('Haryana')),
    (_('Shimla'), _('It is in %s') % _('Himachal Pradesh')),
    (_('Srinagar'), _('It is in %s') % _('Jammu and Kashmir')),
    (_('Ranchi'), _('It is in %s') % _('Jharkhand')),
    (_('Bengalooru'), _('It is in %s') % _('Karnataka')),
    (_('Thiruvananthapuram'), _('It is in %s') % _('Kerala')),
    (_('Bhopal'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Mumbai'), _('It is in %s') % _('Maharashtra')),
    (_('Imphal'), _('It is in %s') % _('Manipur')),
    (_('Shillong'), _('It is in %s') % _('Meghalaya')),
    (_('Aizawl'), _('It is in %s') % _('Mizoram')),
    (_('Kohima'), _('It is in %s') % _('Nagaland')),
    (_('Bhubaneswar'), _('It is in %s') % _('Orissa')),
    (_('Jaipur'), _('It is in %s') % _('Rajasthan')),
    (_('Gangtok'), _('It is in %s') % _('Sikkim')),
    (_('Chennai'), _('It is in %s') % _('Tamil Nadu')),
    (_('Agartala'), _('It is in %s') % _('Tripura')),
    (_('Lucknow'), _('It is in %s') % _('Uttar Pradesh')),
    (_('Dehradun'), _('It is in %s') % _('Uttarakhand')),
    (_('Kolkata'), _('It is in %s') % _('West Bengal')),
    (_('Port Blair'), _('It is in %s') % _('Andaman and Nicobar Islands')),
    (_('Silvassa'), _('It is in %s') % _('Dadra and Nagar Haveli')),
    (_('Daman'), _('It is in %s') % _('Daman and Diu')),
    (_('Kavaratti'), _('It is in %s') % _('Lakshadweep')),
    (_('Pondicherry'), _('It is in %s') % _('Pondicherry')),
    (_('Amarnath'), _('It is in %s') % _('Jammu and Kashmir')),
    (_('Leh'), _('It is in %s') % _('Jammu and Kashmir')),
    (_('Vaishno Devi'), _('It is in %s') % _('Jammu and Kashmir')),
    (_('Patni Top'), _('It is in %s') % _('Jammu and Kashmir')),
    (_('Chamba'), _('It is in %s') % _('Himachal Pradesh')),
    (_('Manali'), _('It is in %s') % _('Himachal Pradesh')),
    (_('Amritsar'), _('It is in %s') % _('Punjab')),
    (_('Atari'), _('It is in %s') % _('Punjab')),
    (_('Bathinda'), _('It is in %s') % _('Punjab')),
    (_('Panipat'), _('It is in %s') % _('Haryana')),
    (_('Kedarnath'), _('It is in %s') % _('Uttarakhand')),
    (_('Badrinath'), _('It is in %s') % _('Uttarakhand')),
    (_('Nainital'), _('It is in %s') % _('Uttarakhand')),
    (_('Sravasti'), _('It is in %s') % _('Uttar Pradesh')),
    (_('Ayodhya'), _('It is in %s') % _('Uttar Pradesh')),
    (_('Agra'), _('It is in %s') % _('Uttar Pradesh')),
    (_('Kanpur'), _('It is in %s') % _('Uttar Pradesh')),
    (_('Varanasi'), _('It is in %s') % _('Uttar Pradesh')),
    (_('Allahabad'), _('It is in %s') % _('Uttar Pradesh')),
    (_('Tezpur'), _('It is in %s') % _('Assam')),
    (_('Darjeeling'), _('It is in %s') % _('West Bengal')),
    (_('Murshidabad'), _('It is in %s') % _('West Bengal')),
    (_('Shantiniketan'), _('It is in %s') % _('West Bengal')),
    (_('Digha'), _('It is in %s') % _('West Bengal')),
    (_('Hazaribag'), _('It is in %s') % _('Jharkhand')),
    (_('Bihar-Sharif'), _('It is in %s') % _('Bihar')),
    (_('Nalanda'), _('It is in %s') % _('Bihar')),
    (_('Bodhgaya'), _('It is in %s') % _('Bihar')),
    (_('Pillani'), _('It is in %s') % _('Rajasthan')),
    (_('Bikaner'), _('It is in %s') % _('Rajasthan')),
    (_('Jaisalmer'), _('It is in %s') % _('Rajasthan')),
    (_('Jodhpur'), _('It is in %s') % _('Rajasthan')),
    (_('Ranakpur'), _('It is in %s') % _('Rajasthan')),
    (_('Bundi'), _('It is in %s') % _('Rajasthan')),
    (_('Kota'), _('It is in %s') % _('Rajasthan')),
    (_('Chittaurgarh'), _('It is in %s') % _('Rajasthan')),
    (_('Mount Abu'), _('It is in %s') % _('Rajasthan')),
    (_('Gwalior'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Shivpuri'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Orchna'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Khajuraho'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Sanchi'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Ujjain'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Indore'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Jabalpur'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Amarkantak'), _('It is in %s') % _('Madhya Pradesh')),
    (_('Ambikapur'), _('It is in %s') % _('Chhattisgarh')),
    (_('Chitrakote Falls'), _('It is in %s') % _('Chhattisgarh')),
    (_('Hirakud Dam'), _('It is in %s') % _('Orissa')),
    (_('Cuttak'), _('It is in %s') % _('Orissa')),
    (_('Paradwip'), _('It is in %s') % _('Orissa')),
    (_('Konarak'), _('It is in %s') % _('Orissa')),
    (_('Puri'), _('It is in %s') % _('Orissa')),
    (_('Gopalpur'), _('It is in %s') % _('Orissa')),
    (_('Bhuj'), _('It is in %s') % _('Gujarat')),
    (_('Lothal'), _('It is in %s') % _('Gujarat')),
    (_('Vadodara'), _('It is in %s') % _('Gujarat')),
    (_('Dwarka'), _('It is in %s') % _('Gujarat')),
    (_('Rajkot'), _('It is in %s') % _('Gujarat')),
    (_('Porbandar'), _('It is in %s') % _('Gujarat')),
    (_('Somnath'), _('It is in %s') % _('Gujarat')),
    (_('Diu'), _('It is in %s') % _('Gujarat')),
    (_('Bhavnagar'), _('It is in %s') % _('Gujarat')),
    (_('Saputara'), _('It is in %s') % _('Gujarat')),
    (_('Malghat'), _('It is in %s') % _('Maharashtra')),
    (_('Wardha'), _('It is in %s') % _('Maharashtra')),
    (_('Chandrapur'), _('It is in %s') % _('Maharashtra')),
    (_('Ajanta'), _('It is in %s') % _('Maharashtra')),
    (_('Ellora'), _('It is in %s') % _('Maharashtra')),
    (_('Aurangabad'), _('It is in %s') % _('Maharashtra')),
    (_('Shirdi'), _('It is in %s') % _('Maharashtra')),
    (_('Pune'), _('It is in %s') % _('Maharashtra')),
    (_('Murud'), _('It is in %s') % _('Maharashtra')),
    (_('Mahabaleshwar'), _('It is in %s') % _('Maharashtra')),
    (_('Ganpatipule'), _('It is in %s') % _('Maharashtra')),
    (_('Panhala'), _('It is in %s') % _('Maharashtra')),
    (_('Warangal'), _('It is in %s') % _('Andhra Pradesh')),
    (_('Vishakhapatnam'), _('It is in %s') % _('Andhra Pradesh')),
    (_('Bhadrachalan'), _('It is in %s') % _('Andhra Pradesh')),
    (_('Amaravati'), _('It is in %s') % _('Andhra Pradesh')),
    (_('Srisailam'), _('It is in %s') % _('Andhra Pradesh')),
    (_('Lepakshi'), _('It is in %s') % _('Andhra Pradesh')),
    (_('Tirupati'), _('It is in %s') % _('Andhra Pradesh')),
    (_('Vasco da Gama'), _('It is in %s') % _('Goa')),
    (_('Bider'), _('It is in %s') % _('Karnataka')),
    (_('Gulbarga'), _('It is in %s') % _('Karnataka')),
    (_('Bijapur'), _('It is in %s') % _('Karnataka')),
    (_('Raichur'), _('It is in %s') % _('Karnataka')),
    (_('Hampi'), _('It is in %s') % _('Karnataka')),
    (_('Jog Falls'), _('It is in %s') % _('Karnataka')),
    (_('Chitradurga'), _('It is in %s') % _('Karnataka')),
    (_('Udupi'), _('It is in %s') % _('Karnataka')),
    (_('Mangalore'), _('It is in %s') % _('Karnataka')),
    (_('Belur'), _('It is in %s') % _('Karnataka')),
    (_('Kozhikode'), _('It is in %s') % _('Kerala')),
    (_('Kochi'), _('It is in %s') % _('Kerala')),
    (_('Alappuzha'), _('It is in %s') % _('Kerala')),
    (_('Mamallpuram'), _('It is in %s') % _('Tamil Nadu')),
    (_('Chidambaram'), _('It is in %s') % _('Tamil Nadu')),
    (_('Mudumali'), _('It is in %s') % _('Tamil Nadu')),
    (_('Thanjavur'), _('It is in %s') % _('Tamil Nadu')),
    (_('Kodaikanal'), _('It is in %s') % _('Tamil Nadu')),
    (_('Madurai'), _('It is in %s') % _('Tamil Nadu')),
    (_('Kanniyakumari'), _('It is in %s') % _('Tamil Nadu')),
    (_('Rameswaram'), _('It is in %s') % _('Tamil Nadu'))    
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3]


